<a href="https://colab.research.google.com/github/Graur/mipt/blob/master/fashion_mnist_dz_graur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import utils
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('fmnist_train.csv')
test_data = pd.read_csv('fmnist_test.csv')

In [3]:
train_data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,Id
0,2,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,9,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,6,0,0,0,0,0,0,0,5,0,...,0.0,0.0,30.0,43.0,0.0,0.0,0.0,0.0,0.0,2
3,0,0,0,0,1,2,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3
4,3,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4

In [4]:
test_data.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,Id
0,0,0,0,0,0,0,0,9,8,0,...,87,56,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,14,53,99,17,...,0,0,0,63,53,31,0,0,0,2
3,0,0,0,0,0,0,0,0,0,161,...,126,140,0,133,224,222,56,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4

In [5]:
train_data.shape

(17040, 786)

In [6]:
test_data.shape

(10000, 785)

In [7]:
classes = ['футболка', 'брюки', 'свитер', 'платье', 'пальто', 'туфли', 'рубашка', 'кроссовки', 'сумка', 'ботинки']

In [19]:
X_train = train_data.drop(['Id', 'label'], axis=1)
y_train = train_data['label']
X_test = test_data.drop(['Id'], axis=1)

In [20]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [12]:
X_test

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784,Id
0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.035294,0.031373,0.000000,...,0.341176,0.219608,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.003922
2,0.0,0.000000,0.000000,0.0,0.0,0.0,0.054902,0.207843,0.388235,0.066667,...,0.000000,0.000000,0.000000,0.247059,0.207843,0.121569,0.000000,0.000000,0.0,0.007843
3,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.631373,...,0.494118,0.549020,0.000000,0.521569,0.878431,0.870588,0.219608,0.000000,0.0,0.011765
4,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.015686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.145098,...,0.090196,0.054902,0.078431,0.000000,0.000000,0.003922,0.000000,0.000000,0.0,39.196078
9996,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.007843,0.203922,0.090196,0.109804,0.000000,0.000000,0.0,39.200000
9997,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.674510,0.674510,0.713725,0.780392,0.870588,0.164706,0.000000,0.003922,0.0,39.203922
9998,0.0,0.003922,0.011765,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.003922,0.000000,0.000000,0.000000,0.0,39.207843
9999,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.549020,0.466667,0.403922,...,0.372549,0.294118,0.172549,0.003922,0.000000,0.000000,0.000000,0.000000,0.0,39.211765

In [21]:
n = 0
print(y_train[n])

2

In [22]:
y_train = utils.to_categorical(y_train, 10)

In [23]:
print(y_train[n])

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]

In [24]:
# Создаем последовательную модель
model = Sequential()
# Входной полносвязный слой, 800 нейронов, 784 входа в каждый нейрон
model.add(Dense(800, input_dim=784, activation="relu"))
# Выходной полносвязный слой, 10 нейронов (по количеству рукописных цифр)
model.add(Dense(10, activation="softmax"))

In [25]:
model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics=["accuracy"])

In [26]:
history = model.fit(X_train, y_train, 
                    batch_size=200, 
                    epochs=100,
                    validation_split=0.2,
                    verbose=1)

Epoch 1/100
69/69 [==============================] - 3s 30ms/step - loss: 1.6974 - accuracy: 0.5091 - val_loss: nan - val_accuracy: 0.6479
Epoch 2/100
69/69 [==============================] - 2s 25ms/step - loss: 1.1359 - accuracy: 0.6776 - val_loss: nan - val_accuracy: 0.6852
Epoch 3/100
69/69 [==============================] - 2s 25ms/step - loss: 0.9463 - accuracy: 0.7145 - val_loss: nan - val_accuracy: 0.7095
Epoch 4/100
69/69 [==============================] - 2s 24ms/step - loss: 0.8493 - accuracy: 0.7383 - val_loss: nan - val_accuracy: 0.7359
Epoch 5/100
69/69 [==============================] - 2s 26ms/step - loss: 0.7877 - accuracy: 0.7577 - val_loss: nan - val_accuracy: 0.7471
Epoch 6/100
69/69 [==============================] - 2s 35ms/step - loss: 0.7432 - accuracy: 0.7716 - val_loss: nan - val_accuracy: 0.7617
Epoch 7/100
69/69 [==============================] - 2s 23ms/step - loss: 0.7097 - accuracy: 0.7801 - val_loss: nan - val_accuracy: 0.7588
Epoch 8/100
69/69 [==============================] - 2s 24ms/step - loss: 0.6828 - accuracy: 0.7886 - val_loss: nan - val_accuracy: 0.7679
Epoch 9/100
69/69 [==============================] - 2s 22ms/step - loss: 0.6601 - accuracy: 0.7932 - val_loss: nan - val_accuracy: 0.7752
Epoch 10/100
69/69 [==============================] - 2s 22ms/step - loss: 0.6419 - accuracy: 0.7967 - val_loss: nan - val_accuracy: 0.7811
Epoch 11/100
69/69 [==============================] - 2s 22ms/step - loss: 0.6251 - accuracy: 0.8028 - val_loss: nan - val_accuracy: 0.7779
Epoch 12/100
69/69 [==============================] - 2s 24ms/step - loss: 0.6115 - accuracy: 0.8070 - val_loss: nan - val_accuracy: 0.7876
Epoch 13/100
69/69 [==============================] - 2s 28ms/step - loss: 0.5984 - accuracy: 0.8108 - val_loss: nan - val_accuracy: 0.7726
Epoch 14/100
69/69 [==============================] - 2s 36ms/step - loss: 0.5879 - accuracy: 0.8124 - val_loss: nan - val_accuracy: 0.7943
Epoch 15/100
69/69 [==============================] - 2s 22ms/step - loss: 0.5767 - accuracy: 0.8143 - val_loss: nan - val_accuracy: 0.8005
Epoch 16/100
69/69 [==============================] - 1s 22ms/step - loss: 0.5686 - accuracy: 0.8170 - val_loss: nan - val_accuracy: 0.8034
Epoch 17/100
69/69 [==============================] - 2s 24ms/step - loss: 0.5591 - accuracy: 0.8210 - val_loss: nan - val_accuracy: 0.8078
Epoch 18/100
69/69 [==============================] - 2s 22ms/step - loss: 0.5519 - accuracy: 0.8231 - val_loss: nan - val_accuracy: 0.8066
Epoch 19/100
69/69 [==============================] - 2s 24ms/step - loss: 0.5452 - accuracy: 0.8248 - val_loss: nan - val_accuracy: 0.8055
Epoch 20/100
69/69 [==============================] - 3s 36ms/step - loss: 0.5383 - accuracy: 0.8253 - val_loss: nan - val_accuracy: 0.8096
Epoch 21/100
69/69 [==============================] - 2s 35ms/step - loss: 0.5320 - accuracy: 0.8284 - val_loss: nan - val_accuracy: 0.8146
Epoch 22/100
69/69 [==============================] - 2s 31ms/step - loss: 0.5261 - accuracy: 0.8288 - val_loss: nan - val_accuracy: 0.8131
Epoch 23/100
69/69 [==============================] - 2s 24ms/step - loss: 0.5210 - accuracy: 0.8307 - val_loss: nan - val_accuracy: 0.8172
Epoch 24/100
69/69 [==============================] - 2s 23ms/step - loss: 0.5158 - accuracy: 0.8314 - val_loss: nan - val_accuracy: 0.8187
Epoch 25/100
69/69 [==============================] - 2s 24ms/step - loss: 0.5113 - accuracy: 0.8338 - val_loss: nan - val_accuracy: 0.8157
Epoch 26/100
69/69 [==============================] - 1s 21ms/step - loss: 0.5069 - accuracy: 0.8353 - val_loss: nan - val_accuracy: 0.8034
Epoch 27/100
69/69 [==============================] - 2s 22ms/step - loss: 0.5031 - accuracy: 0.8360 - val_loss: nan - val_accuracy: 0.8210
Epoch 28/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4988 - accuracy: 0.8361 - val_loss: nan - val_accuracy: 0.8198
Epoch 29/100
69/69 [==============================] - 2s 36ms/step - loss: 0.4952 - accuracy: 0.8371 - val_loss: nan - val_accuracy: 0.8166
Epoch 30/100
69/69 [==============================] - 2s 28ms/step - loss: 0.4917 - accuracy: 0.8368 - val_loss: nan - val_accuracy: 0.8213
Epoch 31/100
69/69 [==============================] - 1s 22ms/step - loss: 0.4882 - accuracy: 0.8385 - val_loss: nan - val_accuracy: 0.8204
Epoch 32/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4842 - accuracy: 0.8385 - val_loss: nan - val_accuracy: 0.8110
Epoch 33/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4820 - accuracy: 0.8405 - val_loss: nan - val_accuracy: 0.8289
Epoch 34/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4787 - accuracy: 0.8403 - val_loss: nan - val_accuracy: 0.8222
Epoch 35/100
69/69 [==============================] - 1s 22ms/step - loss: 0.4755 - accuracy: 0.8419 - val_loss: nan - val_accuracy: 0.8245
Epoch 36/100
69/69 [==============================] - 2s 27ms/step - loss: 0.4729 - accuracy: 0.8432 - val_loss: nan - val_accuracy: 0.8178
Epoch 37/100
69/69 [==============================] - 2s 35ms/step - loss: 0.4704 - accuracy: 0.8426 - val_loss: nan - val_accuracy: 0.8234
Epoch 38/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4672 - accuracy: 0.8418 - val_loss: nan - val_accuracy: 0.8289
Epoch 39/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4652 - accuracy: 0.8442 - val_loss: nan - val_accuracy: 0.8266
Epoch 40/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4626 - accuracy: 0.8441 - val_loss: nan - val_accuracy: 0.8278
Epoch 41/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4602 - accuracy: 0.8454 - val_loss: nan - val_accuracy: 0.8254
Epoch 42/100
69/69 [==============================] - 1s 22ms/step - loss: 0.4580 - accuracy: 0.8455 - val_loss: nan - val_accuracy: 0.8245
Epoch 43/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4555 - accuracy: 0.8462 - val_loss: nan - val_accuracy: 0.8298
Epoch 44/100
69/69 [==============================] - 2s 29ms/step - loss: 0.4530 - accuracy: 0.8465 - val_loss: nan - val_accuracy: 0.8289
Epoch 45/100
69/69 [==============================] - 2s 35ms/step - loss: 0.4513 - accuracy: 0.8479 - val_loss: nan - val_accuracy: 0.8325
Epoch 46/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4498 - accuracy: 0.8473 - val_loss: nan - val_accuracy: 0.8330
Epoch 47/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4473 - accuracy: 0.8475 - val_loss: nan - val_accuracy: 0.8292
Epoch 48/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4445 - accuracy: 0.8493 - val_loss: nan - val_accuracy: 0.8327
Epoch 49/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4427 - accuracy: 0.8507 - val_loss: nan - val_accuracy: 0.8322
Epoch 50/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4416 - accuracy: 0.8491 - val_loss: nan - val_accuracy: 0.8254
Epoch 51/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4392 - accuracy: 0.8519 - val_loss: nan - val_accuracy: 0.8363
Epoch 52/100
69/69 [==============================] - 2s 32ms/step - loss: 0.4378 - accuracy: 0.8498 - val_loss: nan - val_accuracy: 0.8377
Epoch 53/100
69/69 [==============================] - 2s 31ms/step - loss: 0.4358 - accuracy: 0.8526 - val_loss: nan - val_accuracy: 0.8371
Epoch 54/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4348 - accuracy: 0.8517 - val_loss: nan - val_accuracy: 0.8371
Epoch 55/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4320 - accuracy: 0.8545 - val_loss: nan - val_accuracy: 0.8325
Epoch 56/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4310 - accuracy: 0.8545 - val_loss: nan - val_accuracy: 0.8371
Epoch 57/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4294 - accuracy: 0.8544 - val_loss: nan - val_accuracy: 0.8363
Epoch 58/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4278 - accuracy: 0.8547 - val_loss: nan - val_accuracy: 0.8377
Epoch 59/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4263 - accuracy: 0.8564 - val_loss: nan - val_accuracy: 0.8386
Epoch 60/100
69/69 [==============================] - 2s 31ms/step - loss: 0.4251 - accuracy: 0.8561 - val_loss: nan - val_accuracy: 0.8401
Epoch 61/100
69/69 [==============================] - 2s 30ms/step - loss: 0.4232 - accuracy: 0.8552 - val_loss: nan - val_accuracy: 0.8421
Epoch 62/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4214 - accuracy: 0.8564 - val_loss: nan - val_accuracy: 0.8295
Epoch 63/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4210 - accuracy: 0.8573 - val_loss: nan - val_accuracy: 0.8413
Epoch 64/100
69/69 [==============================] - 1s 22ms/step - loss: 0.4191 - accuracy: 0.8572 - val_loss: nan - val_accuracy: 0.8366
Epoch 65/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4182 - accuracy: 0.8570 - val_loss: nan - val_accuracy: 0.8398
Epoch 66/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4162 - accuracy: 0.8581 - val_loss: nan - val_accuracy: 0.8336
Epoch 67/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4151 - accuracy: 0.8581 - val_loss: nan - val_accuracy: 0.8398
Epoch 68/100
69/69 [==============================] - 2s 33ms/step - loss: 0.4132 - accuracy: 0.8591 - val_loss: nan - val_accuracy: 0.8377
Epoch 69/100
69/69 [==============================] - 2s 31ms/step - loss: 0.4124 - accuracy: 0.8586 - val_loss: nan - val_accuracy: 0.8404
Epoch 70/100
69/69 [==============================] - 1s 19ms/step - loss: 0.4110 - accuracy: 0.8578 - val_loss: nan - val_accuracy: 0.8427
Epoch 71/100
69/69 [==============================] - 2s 24ms/step - loss: 0.4098 - accuracy: 0.8611 - val_loss: nan - val_accuracy: 0.8398
Epoch 72/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4082 - accuracy: 0.8603 - val_loss: nan - val_accuracy: 0.8357
Epoch 73/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4077 - accuracy: 0.8616 - val_loss: nan - val_accuracy: 0.8386
Epoch 74/100
69/69 [==============================] - 1s 21ms/step - loss: 0.4061 - accuracy: 0.8616 - val_loss: nan - val_accuracy: 0.8410
Epoch 75/100
69/69 [==============================] - 2s 22ms/step - loss: 0.4044 - accuracy: 0.8622 - val_loss: nan - val_accuracy: 0.8398
Epoch 76/100
69/69 [==============================] - 2s 32ms/step - loss: 0.4032 - accuracy: 0.8622 - val_loss: nan - val_accuracy: 0.8433
Epoch 77/100
69/69 [==============================] - 2s 29ms/step - loss: 0.4030 - accuracy: 0.8622 - val_loss: nan - val_accuracy: 0.8404
Epoch 78/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4012 - accuracy: 0.8619 - val_loss: nan - val_accuracy: 0.8404
Epoch 79/100
69/69 [==============================] - 2s 23ms/step - loss: 0.4003 - accuracy: 0.8630 - val_loss: nan - val_accuracy: 0.8298
Epoch 80/100
69/69 [==============================] - 1s 21ms/step - loss: 0.3992 - accuracy: 0.8639 - val_loss: nan - val_accuracy: 0.8371
Epoch 81/100
69/69 [==============================] - 1s 22ms/step - loss: 0.3985 - accuracy: 0.8647 - val_loss: nan - val_accuracy: 0.8395
Epoch 82/100
69/69 [==============================] - 2s 24ms/step - loss: 0.3964 - accuracy: 0.8672 - val_loss: nan - val_accuracy: 0.8442
Epoch 83/100
69/69 [==============================] - 2s 24ms/step - loss: 0.3957 - accuracy: 0.8644 - val_loss: nan - val_accuracy: 0.8433
Epoch 84/100
69/69 [==============================] - 2s 33ms/step - loss: 0.3945 - accuracy: 0.8650 - val_loss: nan - val_accuracy: 0.8462
Epoch 85/100
69/69 [==============================] - 2s 27ms/step - loss: 0.3931 - accuracy: 0.8658 - val_loss: nan - val_accuracy: 0.8439
Epoch 86/100
69/69 [==============================] - 1s 21ms/step - loss: 0.3923 - accuracy: 0.8667 - val_loss: nan - val_accuracy: 0.8404
Epoch 87/100
69/69 [==============================] - 1s 22ms/step - loss: 0.3918 - accuracy: 0.8659 - val_loss: nan - val_accuracy: 0.8436
Epoch 88/100
69/69 [==============================] - 2s 23ms/step - loss: 0.3910 - accuracy: 0.8670 - val_loss: nan - val_accuracy: 0.8448
Epoch 89/100
69/69 [==============================] - 1s 21ms/step - loss: 0.3892 - accuracy: 0.8680 - val_loss: nan - val_accuracy: 0.8395
Epoch 90/100
69/69 [==============================] - 1s 22ms/step - loss: 0.3888 - accuracy: 0.8684 - val_loss: nan - val_accuracy: 0.8462
Epoch 91/100
69/69 [==============================] - 2s 24ms/step - loss: 0.3870 - accuracy: 0.8691 - val_loss: nan - val_accuracy: 0.8410
Epoch 92/100
69/69 [==============================] - 2s 32ms/step - loss: 0.3868 - accuracy: 0.8675 - val_loss: nan - val_accuracy: 0.8386
Epoch 93/100
69/69 [==============================] - 2s 29ms/step - loss: 0.3858 - accuracy: 0.8695 - val_loss: nan - val_accuracy: 0.8501
Epoch 94/100
69/69 [==============================] - 1s 22ms/step - loss: 0.3854 - accuracy: 0.8685 - val_loss: nan - val_accuracy: 0.8495
Epoch 95/100
69/69 [==============================] - 2s 24ms/step - loss: 0.3831 - accuracy: 0.8694 - val_loss: nan - val_accuracy: 0.8424
Epoch 96/100
69/69 [==============================] - 1s 21ms/step - loss: 0.3832 - accuracy: 0.8689 - val_loss: nan - val_accuracy: 0.8454
Epoch 97/100
69/69 [==============================] - 1s 19ms/step - loss: 0.3817 - accuracy: 0.8699 - val_loss: nan - val_accuracy: 0.8445
Epoch 98/100
69/69 [==============================] - 1s 21ms/step - loss: 0.3807 - accuracy: 0.8691 - val_loss: nan - val_accuracy: 0.8506
Epoch 99/100
69/69 [==============================] - 2s 23ms/step - loss: 0.3802 - accuracy: 0.8697 - val_loss: nan - val_accuracy: 0.8465
Epoch 100/100
69/69 [==============================] - 2s 30ms/step - loss: 0.3789 - accuracy: 0.8716 - val_loss: nan - val_accuracy: 0.8462

In [27]:
scores=model.evaluate(X_train,y_train)

533/533 [==============================] - 3s 5ms/step - loss: nan - accuracy: 0.8644

In [28]:
predictions = model.predict(X_test)

313/313 [==============================] - 2s 5ms/step

In [29]:
predictions

array([[6.6183525e-01, 5.5227224e-06, 3.4013591e-04, ..., 2.7706551e-10,
        2.0724059e-04, 3.8798196e-09],
       [5.8925405e-05, 9.9947804e-01, 2.0613910e-05, ..., 2.7675179e-07,
        1.9466993e-06, 3.6463504e-07],
       [1.9983513e-02, 2.3887619e-02, 5.7428104e-01, ..., 1.4390684e-04,
        5.0009922e-03, 4.8279657e-04],
       ...,
       [7.2603518e-07, 4.6344849e-07, 1.9436066e-04, ..., 8.8516772e-06,
        9.9937683e-01, 8.3674740e-07],
       [1.3164688e-02, 4.2800417e-05, 4.9706303e-02, ..., 3.8045428e-08,
        5.3903532e-01, 5.3286885e-06],
       [6.7892498e-03, 2.1397445e-02, 7.9487735e-01, ..., 1.9095472e-09,
        2.1812053e-04, 4.9908000e-08]], dtype=float32)

In [30]:
predicted_classes = model.predict(X_test).argmax(axis=1)

313/313 [==============================] - 2s 7ms/step

In [31]:
df = pd.DataFrame(zip(range(len(predicted_classes)), list(predicted_classes)), columns=['Id', 'Category'])

In [32]:
df.head()

   Id  Category
0   0         0
1   1         1
2   2         2
3   3         6
4   4         4

In [33]:
df.to_csv('results.csv', index=False)